### PR TITLE
English patches

### PR DESCRIPTION
**Pull request by electronicboy**
Patched up the language a bit inside here too :)

### CODE REVIEW

**Comment by electronicboy** [comment]
That should be it for now! Thanks for the great set of tools, look forward to seeing it where you will take it! :smile:

**Comment by alphartdev** [comment]
Did some testing and it seems all fine :)
Thanks for the correction ! Do you mind if send you some PM on spigot if I need your help (concerning translation) again ?

**Comment by electronicboy** [comment]
Sure, go ahead!

Also, english formats the ending of sentences like "word!" or "word?", as opposed to having a space in-between the punctuation and the word :smile:

**Comment by alphartdev** [comment]
Thanks for the tip, I'm gonna try to remember it :)

**Pull request merged**
